package main

import "fmt"

// DemoVsCsharp 演示 Go vs C# 的核心区别
func DemoVsCsharp() {
	fmt.Println("=== Go vs C# ===")
	fmt.Println()

	fmt.Println("【1】起源与定位")
	fmt.Println("  Go:")
	fmt.Println("    - Google 2009 年发布")
	fmt.Println("    - 系统级语言，目标是云原生")
	fmt.Println("    - 关键字 25 个，语法极简")
	fmt.Println("  C#:")
	fmt.Println("    - Microsoft 2000 年发布")
	fmt.Println("    - 通用面向对象语言，企业级")
	fmt.Println("    - 语法丰富（泛型/LINQ/async/await/属性）")
	fmt.Println()

	fmt.Println("【2】运行时")
	fmt.Println("  Go:")
	fmt.Println("    - 编译为机器码")
	fmt.Println("    - 自带 runtime (几 MB)")
	fmt.Println("    - 单二进制部署")
	fmt.Println("  C#:")
	fmt.Println("    - 编译为 IL（中间语言）")
	fmt.Println("    - .NET CLR 运行时（几十 MB）")
	fmt.Println("    - 自 .NET Core 起也支持单文件部署 (AOT)")
	fmt.Println()

	fmt.Println("【3】并发模型")
	fmt.Println("  Go:")
	fmt.Println("    - goroutine: 2KB 栈")
	fmt.Println("    - channel 通信")
	fmt.Println("    - go func() 一键启动")
	fmt.Println("  C#:")
	fmt.Println("    - Task (基于线程池)")
	fmt.Println("    - async/await + Task<T>")
	fmt.Println("    - TPL (Task Parallel Library)")
	fmt.Println()

	fmt.Println("【4】类型系统")
	fmt.Println("  Go:")
	fmt.Println("    - 接口隐式实现（鸭子类型）")
	fmt.Println("    - 没有 class，只有 struct")
	fmt.Println("    - 没有继承（用组合）")
	fmt.Println("  C#:")
	fmt.Println("    - 必须显式实现接口")
	fmt.Println("    - 完整的 class 体系")
	fmt.Println("    - 继承 (单一) + 多接口实现")
	fmt.Println("    - 泛型比 Go 早 16 年（Go 1.18 才有）")
	fmt.Println()

	fmt.Println("【5】异常处理")
	fmt.Println("  Go:")
	fmt.Println("    - error 是普通返回值")
	fmt.Println("    - panic + recover（少见）")
	fmt.Println("    - 显式处理，无 try-catch")
	fmt.Println("  C#:")
	fmt.Println("    - try-catch-finally")
	fmt.Println("    - 异常类型丰富")
	fmt.Println("    - checked exceptions (Java 风格)")
	fmt.Println()

	fmt.Println("【6】生态")
	fmt.Println("  Go:")
	fmt.Println("    - 云原生 (Docker/K8s 是 Go 写的)")
	fmt.Println("    - DevOps 工具链")
	fmt.Println("    - 微服务")
	fmt.Println("  C#:")
	fmt.Println("    - 企业应用 (.NET 生态)")
	fmt.Println("    - Windows 桌面应用")
	fmt.Println("    - Unity 游戏开发 (主力语言)")
	fmt.Println("    - ASP.NET Core 后端")
	fmt.Println("    - MAUI 跨平台移动")
	fmt.Println()

	fmt.Println("【7】性能")
	fmt.Println("  Go:")
	fmt.Println("    - 启动快，内存低")
	fmt.Println("    - GC 延迟低 (混合写屏障后)")
	fmt.Println("    - 适合高并发服务")
	fmt.Println("  C#:")
	fmt.Println("    - JIT 编译，热身后性能强")
	fmt.Println("    - .NET 7+ 性能大幅提升")
	fmt.Println("    - 适合 CPU 密集 + 企业级")
	fmt.Println()

	fmt.Println("【8】典型场景")
	fmt.Println("  Go:")
	fmt.Println("    - 微服务 / 云原生")
	fmt.Println("    - DevOps 工具（kubectl, docker）")
	fmt.Println("    - 高并发服务（IM/广告）")
	fmt.Println("  C#:")
	fmt.Println("    - 企业内部系统")
	fmt.Println("    - Windows 应用")
	fmt.Println("    - Unity 游戏")
	fmt.Println("    - 跨平台桌面 (MAUI)")
	fmt.Println()

	fmt.Println("📌 选择建议:")
	fmt.Println("   - 云原生/微服务/容器：Go")
	fmt.Println("   - 企业应用/Windows 生态/游戏：C#")
	fmt.Println("   - 简单服务/高并发：Go")
	fmt.Println("   - 复杂业务/重 IDE (Visual Studio)：C#")
	fmt.Println()

	fmt.Println("📌 互通:")
	fmt.Println("   - C# 7+ 的 async/await 和 goroutine 设计哲学类似")
	fmt.Println("   - Go 的 error 风格和 Rust 接近")
	fmt.Println("   - C# 的 record 类型和 Go 的 struct 接近")
}
