services:

  mysql-master:
    image: mysql:8.3
    container_name: mysql-master
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123456
    ports:
      - "3307:3306"
    volumes:
      - master-data:/var/lib/mysql
      - ./master.cnf:/etc/mysql/conf.d/master.cnf
    networks:
      - mysql-repl

  mysql-replica:
    image: mysql:8.3
    container_name: mysql-replica
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123456
    ports:
      - "3308:3306"
    volumes:
      - replica-data:/var/lib/mysql
      - ./replica.cnf:/etc/mysql/conf.d/replica.cnf
    networks:
      - mysql-repl

volumes:
  master-data:
  replica-data:

networks:
  mysql-repl: